/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.unicesumar.map.psii;

/**
 *
 * @author Denilson
 */
public class TelaAtendimento extends javax.swing.JFrame {
    
    Suite su = new Suite();
    Hospede hp = new Hospede();
    Reserva re = new Reserva();
    
    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospede1 = new edu.unicesumar.map.psii.Hospede();
        titulo = new javax.swing.JLabel();
        subTituloCadastro = new javax.swing.JLabel();
        caracteristicaNome = new javax.swing.JLabel();
        boxNome = new javax.swing.JTextField();
        caracteristicaEndereco = new javax.swing.JLabel();
        boxEndereco = new javax.swing.JTextField();
        boxNumero = new javax.swing.JTextField();
        caracteristicaNumero = new javax.swing.JLabel();
        caracteristicaCidade = new javax.swing.JLabel();
        caracteristicaBairro = new javax.swing.JLabel();
        boxCidade = new javax.swing.JTextField();
        boxBairro = new javax.swing.JTextField();
        caracteristicaIdade = new javax.swing.JLabel();
        boxIdade = new javax.swing.JTextField();
        separadorCadastro = new javax.swing.JSeparator();
        subTituloReserva = new javax.swing.JLabel();
        suiteLuxo01 = new javax.swing.JCheckBox();
        suiteLuxo02 = new javax.swing.JCheckBox();
        suiteLuxo03 = new javax.swing.JCheckBox();
        suiteLuxo04 = new javax.swing.JCheckBox();
        suiteLuxo05 = new javax.swing.JCheckBox();
        suiteLuxo06 = new javax.swing.JCheckBox();
        suiteSimples01 = new javax.swing.JCheckBox();
        suiteSimples02 = new javax.swing.JCheckBox();
        suiteSimples03 = new javax.swing.JCheckBox();
        suiteSimples04 = new javax.swing.JCheckBox();
        suiteSimples05 = new javax.swing.JCheckBox();
        suiteSimples06 = new javax.swing.JCheckBox();
        caracteristicaDiaria = new javax.swing.JLabel();
        boxDiaria = new javax.swing.JTextField();
        caracteristicaCriancaAcimaDeDoisAnos = new javax.swing.JLabel();
        boxQuantidadeDePessoas = new javax.swing.JTextField();
        caracteristicaQuantidadeDePessoas = new javax.swing.JLabel();
        criancaAcimaDeDoisAnos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        imprimindoDadosDaReserva = new javax.swing.JTextArea();
        buttonReservaSuite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("SISTEMA DE RESERVA");
        titulo.setToolTipText("");

        subTituloCadastro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        subTituloCadastro.setText("Cadastro do Cliente");

        caracteristicaNome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        caracteristicaNome.setText("Nome");

        boxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNomeActionPerformed(evt);
            }
        });

        caracteristicaEndereco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        caracteristicaEndereco.setText("Endereço");

        boxEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEnderecoActionPerformed(evt);
            }
        });

        caracteristicaNumero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        caracteristicaNumero.setText("Número");

        caracteristicaCidade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        caracteristicaCidade.setText("Cidade");

        caracteristicaBairro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        caracteristicaBairro.setText("Bairro");

        caracteristicaIdade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        caracteristicaIdade.setText("Idade");

        subTituloReserva.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        subTituloReserva.setText("Reserva");

        suiteLuxo01.setText("Suíte Luxo 01, Capacidade de 2, R$: 109.99");
        suiteLuxo01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteLuxo01ActionPerformed(evt);
            }
        });

        suiteLuxo02.setText("Suíte Luxo 02, Capacidade de 3, R$: 129.99");
        suiteLuxo02.setToolTipText("");
        suiteLuxo02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteLuxo02ActionPerformed(evt);
            }
        });

        suiteLuxo03.setText("Suíte Luxo 03, Capacidade de 4, R$ 139.99");
        suiteLuxo03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteLuxo03ActionPerformed(evt);
            }
        });

        suiteLuxo04.setText("Suíte Luxo 04, Capacidade de 2, R$: 109.99");
        suiteLuxo04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteLuxo04ActionPerformed(evt);
            }
        });

        suiteLuxo05.setText("Suíte Luxo 05, Capacidade de 3, R$: 129.99");
        suiteLuxo05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteLuxo05ActionPerformed(evt);
            }
        });

        suiteLuxo06.setText("Suíte Luxo 06, Capacidade de 5, R$: 149.99");
        suiteLuxo06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteLuxo06ActionPerformed(evt);
            }
        });

        suiteSimples01.setText("Suíte Simples 01, Capacidade de 2, R$: 89.99");
        suiteSimples01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteSimples01ActionPerformed(evt);
            }
        });

        suiteSimples02.setText("Suíte Simples 02, Capacidade de 2, R$: 89.99");
        suiteSimples02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteSimples02ActionPerformed(evt);
            }
        });

        suiteSimples03.setText("Suíte Simples 03, Capacidade de 2, R$: 89.99");
        suiteSimples03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteSimples03ActionPerformed(evt);
            }
        });

        suiteSimples04.setText("Suíte Simples 04, Capacidade de 3, R$: 99.99");
        suiteSimples04.setToolTipText("");
        suiteSimples04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteSimples04ActionPerformed(evt);
            }
        });

        suiteSimples05.setText("Suíte Simples 05, Capacidade de 3, R$: 99.99");
        suiteSimples05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteSimples05ActionPerformed(evt);
            }
        });

        suiteSimples06.setText("Suíte Simples 06, Capacidade de 4, R$: 108.99");
        suiteSimples06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteSimples06ActionPerformed(evt);
            }
        });

        caracteristicaDiaria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        caracteristicaDiaria.setText("Quantidade de Diárias:");

        boxDiaria.setText("0");

        caracteristicaCriancaAcimaDeDoisAnos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        caracteristicaCriancaAcimaDeDoisAnos.setText("Crianças acima de 2 anos:");

        boxQuantidadeDePessoas.setText("0");
        boxQuantidadeDePessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxQuantidadeDePessoasActionPerformed(evt);
            }
        });

        caracteristicaQuantidadeDePessoas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        caracteristicaQuantidadeDePessoas.setText("Quantidade de Pessoas:");

        criancaAcimaDeDoisAnos.setText("0");
        criancaAcimaDeDoisAnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criancaAcimaDeDoisAnosActionPerformed(evt);
            }
        });

        imprimindoDadosDaReserva.setColumns(20);
        imprimindoDadosDaReserva.setRows(5);
        jScrollPane1.setViewportView(imprimindoDadosDaReserva);

        buttonReservaSuite.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        buttonReservaSuite.setText("Reservar Suíte");
        buttonReservaSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReservaSuiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTituloReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subTituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caracteristicaNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caracteristicaEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caracteristicaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxNumero)
                            .addComponent(caracteristicaIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxIdade)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caracteristicaCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxCidade, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxBairro)
                            .addComponent(caracteristicaBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                    .addComponent(separadorCadastro)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suiteLuxo01)
                            .addComponent(suiteLuxo02)
                            .addComponent(suiteLuxo03))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(suiteLuxo06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(suiteLuxo05))
                            .addComponent(suiteLuxo04))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suiteSimples02)
                            .addComponent(suiteSimples03)
                            .addComponent(suiteSimples01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suiteSimples04)
                            .addComponent(suiteSimples05)
                            .addComponent(suiteSimples06)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caracteristicaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(caracteristicaQuantidadeDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(boxQuantidadeDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(caracteristicaCriancaAcimaDeDoisAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(criancaAcimaDeDoisAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(boxDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonReservaSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(subTituloCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caracteristicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caracteristicaIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caracteristicaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caracteristicaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caracteristicaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caracteristicaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separadorCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTituloReserva)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(suiteLuxo01)
                                .addComponent(suiteSimples04))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(suiteLuxo02)
                                .addComponent(suiteSimples05))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(suiteLuxo03)
                                .addComponent(suiteSimples06)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(suiteSimples01)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(suiteSimples02)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(suiteSimples03)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(suiteLuxo04)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(suiteLuxo05)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(suiteLuxo06)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caracteristicaDiaria)
                            .addComponent(boxDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caracteristicaQuantidadeDePessoas)
                            .addComponent(boxQuantidadeDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caracteristicaCriancaAcimaDeDoisAnos)
                            .addComponent(criancaAcimaDeDoisAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(buttonReservaSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNomeActionPerformed

    private void boxEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEnderecoActionPerformed

    private void suiteLuxo01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteLuxo01ActionPerformed
        // TODO add your handling code here:        
        su.setNumeroDaSuite(1);
        su.setTipo("Luxo");
        su.setCapacidade(2);
        su.setValorDiaria(109.99);        
    }//GEN-LAST:event_suiteLuxo01ActionPerformed

    private void suiteLuxo02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteLuxo02ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(2);
        su.setTipo("Luxo");
        su.setCapacidade(3);
        su.setValorDiaria(129.99);
    }//GEN-LAST:event_suiteLuxo02ActionPerformed

    private void criancaAcimaDeDoisAnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criancaAcimaDeDoisAnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criancaAcimaDeDoisAnosActionPerformed

    private void boxQuantidadeDePessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxQuantidadeDePessoasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxQuantidadeDePessoasActionPerformed

    private void buttonReservaSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReservaSuiteActionPerformed
        // TODO add your handling code here:  
       imprimindoDadosDaReserva.setText("");
       imprimindoDadosDaReserva.getText();
       hp.setNome(boxNome.getText());
       hp.setIdade(Integer.parseInt(boxIdade.getText()));
       hp.setRua(boxEndereco.getText());
       hp.setNumero(Integer.parseInt(boxNumero.getText()));
       hp.setCidade(boxCidade.getText());
       hp.setBairro(boxBairro.getText());
       
       re.setQuantidadeDiaria(Integer.parseInt(boxDiaria.getText()));
       re.setQuantidadePessoas(Integer.parseInt(boxQuantidadeDePessoas.getText()));
       re.setValorDiaria(su.getValorDiaria());
       re.setCapacidadeSuite(su.getCapacidade());
       re.setQtDeCriancaAcimaDe2Anos(Integer.parseInt(criancaAcimaDeDoisAnos.getText()));
       
       imprimindoDadosDaReserva.append("R$ "+ re.calcularDiaria() + "\n");
       imprimindoDadosDaReserva.append(re.verificarCapacidade());
    }//GEN-LAST:event_buttonReservaSuiteActionPerformed

    private void suiteLuxo04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteLuxo04ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(4);
        su.setTipo("Luxo");
        su.setCapacidade(2);
        su.setValorDiaria(109.99);
    }//GEN-LAST:event_suiteLuxo04ActionPerformed

    private void suiteSimples06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteSimples06ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(6);
        su.setTipo("Simples");
        su.setCapacidade(4);
        su.setValorDiaria(108.99);
    }//GEN-LAST:event_suiteSimples06ActionPerformed

    private void suiteLuxo03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteLuxo03ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(3);
        su.setTipo("Luxo");
        su.setCapacidade(4);
        su.setValorDiaria(139.99);
    }//GEN-LAST:event_suiteLuxo03ActionPerformed

    private void suiteLuxo05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteLuxo05ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(5);
        su.setTipo("Luxo");
        su.setCapacidade(3);
        su.setValorDiaria(129.99);
    }//GEN-LAST:event_suiteLuxo05ActionPerformed

    private void suiteLuxo06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteLuxo06ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(6);
        su.setTipo("Luxo");
        su.setCapacidade(5);
        su.setValorDiaria(149.99);
    }//GEN-LAST:event_suiteLuxo06ActionPerformed

    private void suiteSimples01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteSimples01ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(1);
        su.setTipo("Simples");
        su.setCapacidade(2);
        su.setValorDiaria(89.99);
    }//GEN-LAST:event_suiteSimples01ActionPerformed

    private void suiteSimples02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteSimples02ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(2);
        su.setTipo("Simples");
        su.setCapacidade(2);
        su.setValorDiaria(89.99);
    }//GEN-LAST:event_suiteSimples02ActionPerformed

    private void suiteSimples03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteSimples03ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(3);
        su.setTipo("Simples");
        su.setCapacidade(2);
        su.setValorDiaria(89.99);
    }//GEN-LAST:event_suiteSimples03ActionPerformed

    private void suiteSimples04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteSimples04ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(4);
        su.setTipo("Simples");
        su.setCapacidade(3);
        su.setValorDiaria(99.99);
    }//GEN-LAST:event_suiteSimples04ActionPerformed

    private void suiteSimples05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteSimples05ActionPerformed
        // TODO add your handling code here:
        su.setNumeroDaSuite(5);
        su.setTipo("Simples");
        su.setCapacidade(3);
        su.setValorDiaria(99.99);
    }//GEN-LAST:event_suiteSimples05ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxBairro;
    private javax.swing.JTextField boxCidade;
    private javax.swing.JTextField boxDiaria;
    private javax.swing.JTextField boxEndereco;
    private javax.swing.JTextField boxIdade;
    private javax.swing.JTextField boxNome;
    private javax.swing.JTextField boxNumero;
    private javax.swing.JTextField boxQuantidadeDePessoas;
    private javax.swing.JButton buttonReservaSuite;
    private javax.swing.JLabel caracteristicaBairro;
    private javax.swing.JLabel caracteristicaCidade;
    private javax.swing.JLabel caracteristicaCriancaAcimaDeDoisAnos;
    private javax.swing.JLabel caracteristicaDiaria;
    private javax.swing.JLabel caracteristicaEndereco;
    private javax.swing.JLabel caracteristicaIdade;
    private javax.swing.JLabel caracteristicaNome;
    private javax.swing.JLabel caracteristicaNumero;
    private javax.swing.JLabel caracteristicaQuantidadeDePessoas;
    private javax.swing.JTextField criancaAcimaDeDoisAnos;
    private edu.unicesumar.map.psii.Hospede hospede1;
    private javax.swing.JTextArea imprimindoDadosDaReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator separadorCadastro;
    private javax.swing.JLabel subTituloCadastro;
    private javax.swing.JLabel subTituloReserva;
    private javax.swing.JCheckBox suiteLuxo01;
    private javax.swing.JCheckBox suiteLuxo02;
    private javax.swing.JCheckBox suiteLuxo03;
    private javax.swing.JCheckBox suiteLuxo04;
    private javax.swing.JCheckBox suiteLuxo05;
    private javax.swing.JCheckBox suiteLuxo06;
    private javax.swing.JCheckBox suiteSimples01;
    private javax.swing.JCheckBox suiteSimples02;
    private javax.swing.JCheckBox suiteSimples03;
    private javax.swing.JCheckBox suiteSimples04;
    private javax.swing.JCheckBox suiteSimples05;
    private javax.swing.JCheckBox suiteSimples06;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
